activeEnv: testEnv
browser:
  browserName: chrome
  browserAttachScreenshot: false
  headlessMode: false
  browserTimeout: 6
environments:
  testEnv:
    envName: testEnv
    appUrl: http://146.59.32.4/index.php/
    title: TesterSii
    email: Johan23@test.pl
    firstName: Johan
    lastName: Tarkov
    password: password
    birthDate: 12/30/1994
    searchValue: HUMMINGBIRD
    basketTestProduct: THE BEST IS YET POSTER
    basketProductsAmount: 3
    basketProductPrice: "29.00"
    basketText1: "There are "
    basketText2: " items in your cart."
    filteredResultsText1: "There are "
    filteredResultsText2: " products."
    filtersLowestPrice: 9.00
    filtersHighestPrice: 10.00
  intEnv:
    envName: intEnv
    appUrl: https://www.selenium.dev/
    title: Selenium